// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vvortex_afu_shim.h for the primary calling header

#include "Vvortex_afu_shim__pch.h"

void Vvortex_afu_shim___024root___nba_sequent__TOP__0(Vvortex_afu_shim___024root* vlSelf);
void Vvortex_afu_shim___024root___nba_sequent__TOP__1(Vvortex_afu_shim___024root* vlSelf);
void Vvortex_afu_shim___024root___nba_sequent__TOP__2(Vvortex_afu_shim___024root* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__0(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_writeback_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__operands__DOT__g_collectors__BRA__0__KET____DOT__opc_writeback_if__0(Vvortex_afu_shim_VX_writeback_if* vlSelf);
void Vvortex_afu_shim_VX_scoreboard_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard_if__0(Vvortex_afu_shim_VX_scoreboard_if* vlSelf);
void Vvortex_afu_shim_VX_mem_bus_if__D4_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__arb_core_bus_if__BRA__0__KET____0(Vvortex_afu_shim_VX_mem_bus_if__D4_T3* vlSelf);
void Vvortex_afu_shim_VX_result_if__Tz92___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__g_blocks__BRA__0__KET____DOT__lsu_slice__DOT__result_no_rsp_if__0(Vvortex_afu_shim_VX_result_if__Tz92* vlSelf);
void Vvortex_afu_shim_VX_writeback_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__writeback_if__BRA__0__KET____0(Vvortex_afu_shim_VX_writeback_if* vlSelf);
void Vvortex_afu_shim_VX_execute_if__Tz83___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_blocks__BRA__0__KET____DOT__pe_execute_if__BRA__0__KET____0(Vvortex_afu_shim_VX_execute_if__Tz83* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET____0(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET____0(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET____0(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET____0(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim_VX_schedule_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__schedule_if__0(Vvortex_afu_shim_VX_schedule_if* vlSelf);
void Vvortex_afu_shim_VX_mem_bus_if__D4_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET____0(Vvortex_afu_shim_VX_mem_bus_if__D4_T3* vlSelf);
void Vvortex_afu_shim_VX_mem_bus_if__D10_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__core_bus_cache_if__BRA__0__KET____0(Vvortex_afu_shim_VX_mem_bus_if__D10_T3* vlSelf);
void Vvortex_afu_shim_VX_mem_bus_if__D10_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__arb_core_bus_if__BRA__0__KET____0(Vvortex_afu_shim_VX_mem_bus_if__D10_T3* vlSelf);
void Vvortex_afu_shim_VX_issue_sched_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue_sched_if__BRA__0__KET____0(Vvortex_afu_shim_VX_issue_sched_if* vlSelf);
void Vvortex_afu_shim___024root___nba_sequent__TOP__3(Vvortex_afu_shim___024root* vlSelf);
void Vvortex_afu_shim_VX_mem_bus_if__D4_T2___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__1__KET____0(Vvortex_afu_shim_VX_mem_bus_if__D4_T2* vlSelf);
void Vvortex_afu_shim_VX_mem_bus_if__D4_T2___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__0__KET____0(Vvortex_afu_shim_VX_mem_bus_if__D4_T2* vlSelf);
void Vvortex_afu_shim_VX_decode_sched_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__decode_sched_if__0(Vvortex_afu_shim_VX_decode_sched_if* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_mem_bus_if__D10_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET____0(Vvortex_afu_shim_VX_mem_bus_if__D10_T3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET____1(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET____1(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__1(Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET____1(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET____1(Vvortex_afu_shim_VX_ibuffer_if* vlSelf);
void Vvortex_afu_shim___024root___nba_sequent__TOP__4(Vvortex_afu_shim___024root* vlSelf);

void Vvortex_afu_shim___024root___eval_nba(Vvortex_afu_shim___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vvortex_afu_shim___024root___eval_nba\n"); );
    Vvortex_afu_shim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if ((1ULL & vlSelfRef.__VnbaTriggered[0U])) {
        Vvortex_afu_shim___024root___nba_sequent__TOP__0(vlSelf);
        Vvortex_afu_shim___024root___nba_sequent__TOP__1(vlSelf);
        Vvortex_afu_shim___024root___nba_sequent__TOP__2(vlSelf);
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_writeback_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__operands__DOT__g_collectors__BRA__0__KET____DOT__opc_writeback_if__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__operands__DOT__g_collectors__BRA__0__KET____DOT__opc_writeback_if));
        Vvortex_afu_shim_VX_scoreboard_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard_if__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard_if));
        Vvortex_afu_shim_VX_mem_bus_if__D4_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__arb_core_bus_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__arb_core_bus_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_result_if__Tz92___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__g_blocks__BRA__0__KET____DOT__lsu_slice__DOT__result_no_rsp_if__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__g_blocks__BRA__0__KET____DOT__lsu_slice__DOT__result_no_rsp_if));
        Vvortex_afu_shim_VX_writeback_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__writeback_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__writeback_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_execute_if__Tz83___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_blocks__BRA__0__KET____DOT__pe_execute_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_blocks__BRA__0__KET____DOT__pe_execute_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET__));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET__));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET__));
        Vvortex_afu_shim_VX_schedule_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__schedule_if__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__schedule_if));
        Vvortex_afu_shim_VX_mem_bus_if__D4_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_mem_bus_if__D10_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__core_bus_cache_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__core_bus_cache_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_mem_bus_if__D10_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__arb_core_bus_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__arb_core_bus_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_issue_sched_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue_sched_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue_sched_if__BRA__0__KET__));
        Vvortex_afu_shim___024root___nba_sequent__TOP__3(vlSelf);
        Vvortex_afu_shim_VX_mem_bus_if__D4_T2___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__1__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__1__KET__));
        Vvortex_afu_shim_VX_mem_bus_if__D4_T2___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_decode_sched_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__decode_sched_if__0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__decode_sched_if));
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_mem_bus_if__D10_T3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET____0((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET__));
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D31_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET____1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET__));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET____1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET__));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_stream_arb__N4_D22_Az17_O3___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb__1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET____1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET__));
        Vvortex_afu_shim_VX_ibuffer_if___nba_sequent__TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET____1((&vlSymsp->TOP__vortex_afu_shim__DOT__afu_wrap__DOT__vortex_axi__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET__));
        Vvortex_afu_shim___024root___nba_sequent__TOP__4(vlSelf);
    }
}

void Vvortex_afu_shim___024root___trigger_orInto__act_vec_vec(VlUnpacked<QData/*63:0*/, 1> &out, const VlUnpacked<QData/*63:0*/, 1> &in) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vvortex_afu_shim___024root___trigger_orInto__act_vec_vec\n"); );
    // Locals
    IData/*31:0*/ n;
    // Body
    n = 0U;
    do {
        out[n] = (out[n] | in[n]);
        n = ((IData)(1U) + n);
    } while ((0U >= n));
}

void Vvortex_afu_shim___024root___eval_triggers_vec__act(Vvortex_afu_shim___024root* vlSelf);
#ifdef VL_DEBUG
VL_ATTR_COLD void Vvortex_afu_shim___024root___dump_triggers__act(const VlUnpacked<QData/*63:0*/, 1> &triggers, const std::string &tag);
#endif  // VL_DEBUG

bool Vvortex_afu_shim___024root___eval_phase__act(Vvortex_afu_shim___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vvortex_afu_shim___024root___eval_phase__act\n"); );
    Vvortex_afu_shim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vvortex_afu_shim___024root___eval_triggers_vec__act(vlSelf);
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vvortex_afu_shim___024root___dump_triggers__act(vlSelfRef.__VactTriggered, "act"s);
    }
#endif
    Vvortex_afu_shim___024root___trigger_orInto__act_vec_vec(vlSelfRef.__VnbaTriggered, vlSelfRef.__VactTriggered);
    return (0U);
}

void Vvortex_afu_shim___024root___trigger_clear__act(VlUnpacked<QData/*63:0*/, 1> &out) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vvortex_afu_shim___024root___trigger_clear__act\n"); );
    // Locals
    IData/*31:0*/ n;
    // Body
    n = 0U;
    do {
        out[n] = 0ULL;
        n = ((IData)(1U) + n);
    } while ((1U > n));
}

bool Vvortex_afu_shim___024root___trigger_anySet__act(const VlUnpacked<QData/*63:0*/, 1> &in);

bool Vvortex_afu_shim___024root___eval_phase__nba(Vvortex_afu_shim___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vvortex_afu_shim___024root___eval_phase__nba\n"); );
    Vvortex_afu_shim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Locals
    CData/*0:0*/ __VnbaExecute;
    // Body
    __VnbaExecute = Vvortex_afu_shim___024root___trigger_anySet__act(vlSelfRef.__VnbaTriggered);
    if (__VnbaExecute) {
        Vvortex_afu_shim___024root___eval_nba(vlSelf);
        Vvortex_afu_shim___024root___trigger_clear__act(vlSelfRef.__VnbaTriggered);
    }
    return (__VnbaExecute);
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vvortex_afu_shim___024root___dump_triggers__ico(const VlUnpacked<QData/*63:0*/, 1> &triggers, const std::string &tag);
#endif  // VL_DEBUG
bool Vvortex_afu_shim___024root___eval_phase__ico(Vvortex_afu_shim___024root* vlSelf);

void Vvortex_afu_shim___024root___eval(Vvortex_afu_shim___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vvortex_afu_shim___024root___eval\n"); );
    Vvortex_afu_shim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Locals
    IData/*31:0*/ __VicoIterCount;
    IData/*31:0*/ __VnbaIterCount;
    // Body
    __VicoIterCount = 0U;
    vlSelfRef.__VicoFirstIteration = 1U;
    do {
        if (VL_UNLIKELY(((0x00000064U < __VicoIterCount)))) {
#ifdef VL_DEBUG
            Vvortex_afu_shim___024root___dump_triggers__ico(vlSelfRef.__VicoTriggered, "ico"s);
#endif
            VL_FATAL_MT("/vortex/sim/xrtsim/vortex_afu_shim.sv", 16, "", "DIDNOTCONVERGE: Input combinational region did not converge after '--converge-limit' of 100 tries");
        }
        __VicoIterCount = ((IData)(1U) + __VicoIterCount);
        vlSelfRef.__VicoPhaseResult = Vvortex_afu_shim___024root___eval_phase__ico(vlSelf);
        vlSelfRef.__VicoFirstIteration = 0U;
    } while (vlSelfRef.__VicoPhaseResult);
    __VnbaIterCount = 0U;
    do {
        if (VL_UNLIKELY(((0x00000064U < __VnbaIterCount)))) {
#ifdef VL_DEBUG
            Vvortex_afu_shim___024root___dump_triggers__act(vlSelfRef.__VnbaTriggered, "nba"s);
#endif
            VL_FATAL_MT("/vortex/sim/xrtsim/vortex_afu_shim.sv", 16, "", "DIDNOTCONVERGE: NBA region did not converge after '--converge-limit' of 100 tries");
        }
        __VnbaIterCount = ((IData)(1U) + __VnbaIterCount);
        vlSelfRef.__VactIterCount = 0U;
        do {
            if (VL_UNLIKELY(((0x00000064U < vlSelfRef.__VactIterCount)))) {
#ifdef VL_DEBUG
                Vvortex_afu_shim___024root___dump_triggers__act(vlSelfRef.__VactTriggered, "act"s);
#endif
                VL_FATAL_MT("/vortex/sim/xrtsim/vortex_afu_shim.sv", 16, "", "DIDNOTCONVERGE: Active region did not converge after '--converge-limit' of 100 tries");
            }
            vlSelfRef.__VactIterCount = ((IData)(1U) 
                                         + vlSelfRef.__VactIterCount);
            vlSelfRef.__VactPhaseResult = Vvortex_afu_shim___024root___eval_phase__act(vlSelf);
        } while (vlSelfRef.__VactPhaseResult);
        vlSelfRef.__VnbaPhaseResult = Vvortex_afu_shim___024root___eval_phase__nba(vlSelf);
    } while (vlSelfRef.__VnbaPhaseResult);
}

#ifdef VL_DEBUG
void Vvortex_afu_shim___024root___eval_debug_assertions(Vvortex_afu_shim___024root* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vvortex_afu_shim___024root___eval_debug_assertions\n"); );
    Vvortex_afu_shim__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    if (VL_UNLIKELY(((vlSelfRef.ap_clk & 0xfeU)))) {
        Verilated::overWidthError("ap_clk");
    }
    if (VL_UNLIKELY(((vlSelfRef.ap_rst_n & 0xfeU)))) {
        Verilated::overWidthError("ap_rst_n");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_7_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_7_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_7_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_7_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_7_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_7_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_7_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_7_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_7_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_6_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_6_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_6_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_6_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_6_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_6_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_6_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_6_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_6_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_5_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_5_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_5_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_5_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_5_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_5_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_5_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_5_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_5_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_4_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_4_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_4_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_4_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_4_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_4_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_4_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_4_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_4_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_3_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_3_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_3_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_3_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_3_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_3_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_3_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_3_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_3_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_2_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_2_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_2_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_2_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_2_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_2_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_2_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_2_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_2_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_1_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_1_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_1_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_1_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_1_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_1_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_1_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_1_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_1_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_awready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_0_awready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_wready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_0_wready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_arready 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_0_arready");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_rvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_0_rvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_rlast & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_0_rlast");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_rresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_0_rresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_bvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("m_axi_mem_0_bvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.m_axi_mem_0_bresp & 0xfcU)))) {
        Verilated::overWidthError("m_axi_mem_0_bresp");
    }
    if (VL_UNLIKELY(((vlSelfRef.s_axi_ctrl_awvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("s_axi_ctrl_awvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.s_axi_ctrl_wvalid & 0xfeU)))) {
        Verilated::overWidthError("s_axi_ctrl_wvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.s_axi_ctrl_wstrb & 0xf0U)))) {
        Verilated::overWidthError("s_axi_ctrl_wstrb");
    }
    if (VL_UNLIKELY(((vlSelfRef.s_axi_ctrl_arvalid 
                      & 0xfeU)))) {
        Verilated::overWidthError("s_axi_ctrl_arvalid");
    }
    if (VL_UNLIKELY(((vlSelfRef.s_axi_ctrl_rready & 0xfeU)))) {
        Verilated::overWidthError("s_axi_ctrl_rready");
    }
    if (VL_UNLIKELY(((vlSelfRef.s_axi_ctrl_bready & 0xfeU)))) {
        Verilated::overWidthError("s_axi_ctrl_bready");
    }
}
#endif  // VL_DEBUG
