// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary model header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VVORTEX_AFU_SHIM_H_
#define VERILATED_VVORTEX_AFU_SHIM_H_  // guard

#include "verilated.h"
#include "svdpi.h"

class Vvortex_afu_shim__Syms;
class Vvortex_afu_shim___024root;
class Vvortex_afu_shim_VX_decode_sched_if;
class Vvortex_afu_shim_VX_execute_if__Tz85;
class Vvortex_afu_shim_VX_fifo_queue__D200;
class Vvortex_afu_shim_VX_fifo_queue__D2b;
class Vvortex_afu_shim_VX_ibuffer_if;
class Vvortex_afu_shim_VX_issue_sched_if;
class Vvortex_afu_shim_VX_mem_bus_if__D10_T3;
class Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2a;
class Vvortex_afu_shim_VX_mem_bus_if__D40_T5;
class Vvortex_afu_shim_VX_mem_bus_if__D4_T2;
class Vvortex_afu_shim_VX_mem_bus_if__D4_T3;
class Vvortex_afu_shim_VX_operands_if;
class Vvortex_afu_shim_VX_result_if__Tz103;
class Vvortex_afu_shim_VX_result_if__Tz86;
class Vvortex_afu_shim_VX_result_if__Tz94;
class Vvortex_afu_shim_VX_result_if__Tz99;
class Vvortex_afu_shim_VX_schedule_if;
class Vvortex_afu_shim_VX_scoreboard_if;
class Vvortex_afu_shim_VX_stream_arb__N4_D22_Az1_O3;
class Vvortex_afu_shim_VX_stream_arb__N4_D31_Az1_O3;
class Vvortex_afu_shim_VX_writeback_if;
class Vvortex_afu_shim___024unit;


// This class is the main interface to the Verilated model
class alignas(VL_CACHE_LINE_BYTES) Vvortex_afu_shim VL_NOT_FINAL : public VerilatedModel {
  private:
    // Symbol table holding complete model state (owned by this class)
    Vvortex_afu_shim__Syms* const vlSymsp;

  public:

    // CONSTEXPR CAPABILITIES
    // Verilated with --trace?
    static constexpr bool traceCapable = false;

    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(&clk,0,0);
    VL_IN8(&reset,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_TxAlmFull,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_TxAlmFull,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_vc_used,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_rsvd1,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_hit_miss,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_rsvd0,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_cl_num,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_hdr_resp_type,3,0);
    VL_IN8(&vcp2af_sRxPort_c0_rspValid,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_mmioRdValid,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_mmioWrValid,0,0);
    VL_IN8(&vcp2af_sRxPort_c0_ReqMmioHdr_length,1,0);
    VL_IN8(&vcp2af_sRxPort_c0_ReqMmioHdr_rsvd,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_vc_used,1,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_rsvd1,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_hit_miss,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_format,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_rsvd0,0,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_cl_num,1,0);
    VL_IN8(&vcp2af_sRxPort_c1_hdr_resp_type,3,0);
    VL_IN8(&vcp2af_sRxPort_c1_rspValid,0,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_vc_sel,1,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_rsvd1,1,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_cl_len,1,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_req_type,3,0);
    VL_OUT8(&af2cp_sTxPort_c0_hdr_rsvd0,5,0);
    VL_OUT8(&af2cp_sTxPort_c0_valid,0,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_rsvd2,5,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_vc_sel,1,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_sop,0,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_rsvd1,0,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_cl_len,1,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_req_type,3,0);
    VL_OUT8(&af2cp_sTxPort_c1_hdr_rsvd0,5,0);
    VL_OUT8(&af2cp_sTxPort_c1_valid,0,0);
    VL_OUT8(&af2cp_sTxPort_c2_mmioRdValid,0,0);
    VL_IN16(&vcp2af_sRxPort_c0_hdr_mdata,15,0);
    VL_IN16(&vcp2af_sRxPort_c0_ReqMmioHdr_address,15,0);
    VL_IN16(&vcp2af_sRxPort_c0_ReqMmioHdr_tid,8,0);
    VL_IN16(&vcp2af_sRxPort_c1_hdr_mdata,15,0);
    VL_OUT16(&af2cp_sTxPort_c0_hdr_mdata,15,0);
    VL_OUT16(&af2cp_sTxPort_c1_hdr_mdata,15,0);
    VL_OUT16(&af2cp_sTxPort_c2_hdr_tid,8,0);
    VL_INW(&vcp2af_sRxPort_c0_data,511,0,16);
    VL_OUTW(&af2cp_sTxPort_c1_data,511,0,16);
    VL_OUT64(&af2cp_sTxPort_c0_hdr_address,41,0);
    VL_OUT64(&af2cp_sTxPort_c1_hdr_address,41,0);
    VL_OUT64(&af2cp_sTxPort_c2_data,63,0);
    VL_OUTW((&avs_writedata)[8],511,0,16);
    VL_INW((&avs_readdata)[8],511,0,16);
    VL_OUT((&avs_address)[8],22,0);
    VL_IN8((&avs_waitrequest)[8],0,0);
    VL_OUT8((&avs_write)[8],0,0);
    VL_OUT8((&avs_read)[8],0,0);
    VL_OUT64((&avs_byteenable)[8],63,0);
    VL_OUT8((&avs_burstcount)[8],3,0);
    VL_IN8((&avs_readdatavalid)[8],0,0);

    // CELLS
    // Public to allow access to /* verilator public */ items.
    // Otherwise the application code can consider these internals.
    Vvortex_afu_shim___024unit* const __PVT____024unit;
    Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2a* const __PVT__vortex_afu_shim__DOT__afu__DOT__vx_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2a* const __PVT__vortex_afu_shim__DOT__afu__DOT__cci_vx_mem_arb_in_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_A1a_T2a* const __PVT__vortex_afu_shim__DOT__afu__DOT__cci_vx_mem_arb_in_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__0__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__1__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__2__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__3__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__4__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__5__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__6__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D2b* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_req_xbar_data_out__BRA__7__KET____DOT__rd_req_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__0__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__1__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__2__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__3__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__4__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__5__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__6__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_fifo_queue__D200* const __PVT__vortex_afu_shim__DOT__afu__DOT__avs_adapter__DOT__g_rsp_xbar_data_in__BRA__7__KET____DOT__rsp_queue;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__l3cache__DOT__mem_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__l2cache__DOT__mem_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__per_core_icache_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__per_core_dcache_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__cache_mem_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__arb_core_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_core_arb__BRA__0__KET____DOT__core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_core_arb__BRA__0__KET____DOT__arb_core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_mem_bus_if__BRA__0__KET____DOT__arb_core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_mem_bus_if__BRA__0__KET____DOT__mem_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__core_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__mem_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__mem_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__icache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__mem_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__arb_core_bus_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_core_arb__BRA__0__KET____DOT__core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_core_arb__BRA__0__KET____DOT__arb_core_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__core_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__mem_bus_cache_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_bypass__DOT__cache_bypass__DOT__core_bus_nc_switch_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_bypass__DOT__cache_bypass__DOT__core_bus_nc_switch_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_bypass__DOT__cache_bypass__DOT__core_bus_in_nc_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_bypass__DOT__cache_bypass__DOT__core_bus_nc_arb_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_bypass__DOT__cache_bypass__DOT__mem_bus_out_nc_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_bypass__DOT__cache_bypass__DOT__mem_bus_out_src_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_bypass__DOT__cache_bypass__DOT__mem_bus_out_src_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__core_bus2_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D40_T5* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__dcache__DOT__g_cache_wrap__BRA__0__KET____DOT__cache_wrap__DOT__g_cache__DOT__cache__DOT__mem_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_schedule_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__schedule_if;
    Vvortex_afu_shim_VX_decode_sched_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__decode_sched_if;
    Vvortex_afu_shim_VX_issue_sched_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue_sched_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_writeback_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__writeback_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_scoreboard_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard_if;
    Vvortex_afu_shim_VX_operands_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__operands_if;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer__DOT__g_instr_bufs__BRA__0__KET____DOT__uop_sequencer_if;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer__DOT__g_instr_bufs__BRA__1__KET____DOT__uop_sequencer_if;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer__DOT__g_instr_bufs__BRA__2__KET____DOT__uop_sequencer_if;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__ibuffer__DOT__g_instr_bufs__BRA__3__KET____DOT__uop_sequencer_if;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_ibuffer_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__scoreboard__DOT__staging_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_operands_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__operands__DOT__per_opc_operands_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_scoreboard_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__operands__DOT__g_collectors__BRA__0__KET____DOT__opc_scoreboard_if;
    Vvortex_afu_shim_VX_writeback_if* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__issue__DOT__g_slices__BRA__0__KET____DOT__issue_slice__DOT__operands__DOT__g_collectors__BRA__0__KET____DOT__opc_writeback_if;
    Vvortex_afu_shim_VX_execute_if__Tz85* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__per_block_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_result_if__Tz86* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__per_block_result_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_execute_if__Tz85* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_blocks__BRA__0__KET____DOT__pe_execute_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_execute_if__Tz85* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_blocks__BRA__0__KET____DOT__pe_execute_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_result_if__Tz86* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_blocks__BRA__0__KET____DOT__pe_result_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_result_if__Tz86* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__alu_unit__DOT__g_blocks__BRA__0__KET____DOT__pe_result_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_result_if__Tz94* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__per_block_result_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_result_if__Tz94* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__g_blocks__BRA__0__KET____DOT__lsu_slice__DOT__result_rsp_if;
    Vvortex_afu_shim_VX_result_if__Tz94* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__lsu_unit__DOT__g_blocks__BRA__0__KET____DOT__lsu_slice__DOT__result_no_rsp_if;
    Vvortex_afu_shim_VX_result_if__Tz99* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__fpu_unit__DOT__per_block_result_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_result_if__Tz103* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__per_block_result_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_result_if__Tz103* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__pe_result_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_result_if__Tz103* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__execute__DOT__sfu_unit__DOT__pe_result_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__3__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__2__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__1__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D4_T2* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__lmem_adapt_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_mem_bus_if__D10_T3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__g_dcache_adapters__BRA__0__KET____DOT__dcache_bus_tmp_if__BRA__0__KET__;
    Vvortex_afu_shim_VX_stream_arb__N4_D31_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb;
    Vvortex_afu_shim_VX_stream_arb__N4_D31_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb;
    Vvortex_afu_shim_VX_stream_arb__N4_D31_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb;
    Vvortex_afu_shim_VX_stream_arb__N4_D31_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__req_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb;
    Vvortex_afu_shim_VX_stream_arb__N4_D22_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__0__KET____DOT__xbar_arb;
    Vvortex_afu_shim_VX_stream_arb__N4_D22_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__1__KET____DOT__xbar_arb;
    Vvortex_afu_shim_VX_stream_arb__N4_D22_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__2__KET____DOT__xbar_arb;
    Vvortex_afu_shim_VX_stream_arb__N4_D22_Az1_O3* const __PVT__vortex_afu_shim__DOT__afu__DOT__vortex__DOT__g_clusters__BRA__0__KET____DOT__cluster__DOT__g_sockets__BRA__0__KET____DOT__socket__DOT__g_cores__BRA__0__KET____DOT__core__DOT__mem_unit__DOT__local_mem__DOT__rsp_xbar__DOT__g_multi_inputs__DOT__g_multiple_outputs__DOT__g_xbar_arbs__BRA__3__KET____DOT__xbar_arb;

    // Root instance pointer to allow access to model internals,
    // including inlined /* verilator public_flat_* */ items.
    Vvortex_afu_shim___024root* const rootp;

    // CONSTRUCTORS
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    explicit Vvortex_afu_shim(VerilatedContext* contextp, const char* name = "TOP");
    explicit Vvortex_afu_shim(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    virtual ~Vvortex_afu_shim();
  private:
    VL_UNCOPYABLE(Vvortex_afu_shim);  ///< Copying not allowed

  public:
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    /// Are there scheduled events to handle?
    bool eventsPending();
    /// Returns time at next time slot. Aborts if !eventsPending()
    uint64_t nextTimeSlot();
    /// Trace signals in the model; called by application code
    void trace(VerilatedTraceBaseC* tfp, int levels, int options = 0) { contextp()->trace(tfp, levels, options); }
    /// Retrieve name of this model instance (as passed to constructor).
    const char* name() const;

    // Abstract methods from VerilatedModel
    const char* hierName() const override final;
    const char* modelName() const override final;
    unsigned threads() const override final;
    /// Prepare for cloning the model at the process level (e.g. fork in Linux)
    /// Release necessary resources. Called before cloning.
    void prepareClone() const;
    /// Re-init after cloning the model at the process level (e.g. fork in Linux)
    /// Re-allocate necessary resources. Called after cloning.
    void atClone() const;
  private:
    // Internal functions - trace registration
    void traceBaseModel(VerilatedTraceBaseC* tfp, int levels, int options);
};

#endif  // guard
